# This is a basic workflow to help you get started with Actions

name: freelec-springboot2-webservice

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #   push:
  #     branches: [ "master" ]
  #   pull_request:
  #     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Environment Variables
# https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
env:
  S3_BUCKET_NAME: freelec-springboot2-webservice-deploy
  PROJECT_NAME: freelec-springboot2-webservice

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      
      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      # Connect S3 for uploading application jar
      - name: Zip and Move Before Deploy
        run: |
          zip -r $PROJECT_NAME *
          mkdir -p deploy
          mv $PROJECT_NAME.zip deploy/$PROJECT_NAME.zip
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with: # https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        
        # AWS CLI Command
        # https://docs.aws.amazon.com/ko_kr/cli/latest/userguide/cli-services-s3-commands.html#using-s3-commands-managing-objects
      - name: Upload jar to S3
        run: aws s3 cp --region ap-northeast-2 ./deploy/$PROJECT_NAME.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/$PROJECT_NAME.zip

        # CodeDeploy settings
      - name: Code Deploy
        run: aws deploy create-deployment --application-name freelec-springboot2-webservice-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name develop --s3-location bucket=$SS3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$PROJECT_NAME.zip
